-- AlterTable
ALTER TABLE `Invoice` MODIFY `invoiceType` ENUM('RENT', 'TAX', 'INSURANCE', 'REGISTRATION', 'MAINTENANCE', 'CONTRACT_EXPENSE', 'OTHER_EXPENSE', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `Payment` ADD COLUMN `title` VARCHAR(191) NULL,
    MODIFY `paymentType` ENUM('RENT', 'TAX', 'INSURANCE', 'REGISTRATION', 'MAINTENANCE', 'CONTRACT_EXPENSE', 'OTHER_EXPENSE', 'OTHER') NULL;
