import "./globals.css";
import DashboardNav from "@/app/components/Navbar/Navbar";
import { Rtl } from "@/app/components/Rtl/Rtl";
import { SubmitLoaderProvider } from "@/app/context/SubmitLoaderProvider/SubmitLoaderProvider";
import { DataLoaderProvider } from "@/app/context/DataLoaderProvider/DataLoaderProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className>
        <DataLoaderProvider>
          <SubmitLoaderProvider>
            <Rtl>
              <DashboardNav>{children}</DashboardNav>
            </Rtl>
          </SubmitLoaderProvider>
        </DataLoaderProvider>
      </body>
    </html>
  );
}
