-- AlterTable
ALTER TABLE `Invoice` MODIFY `invoiceType` ENUM('RENT', 'TAX', 'INSURANCE', 'REGISTRATION', 'MAINTENANCE', 'CONTRACT_EXPENSE', 'OTHER') NOT NULL;

-- AlterTable
ALTER TABLE `Payment` MODIFY `paymentType` ENUM('RENT', 'TAX', 'INSURANCE', 'REGISTRATION', 'MAINTENANCE', 'CONTRACT_EXPENSE', 'OTHER') NULL;
