-- AlterTable
ALTER TABLE `Invoice` ADD COLUMN `invoiceType` ENUM('RENT', 'TAX', 'INSURANCE', 'REGISTRATION') NULL,
    ADD COLUMN `paidAmount` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `title` VARCHAR(191) NULL;
